---
title: "Lista 07"
author: "Alan Rodrigo Panosso"
date: "21/09/2020"
output: html_document
---

# Resolução Lista 07

### Carregando os pacotes
```{r}
library(agricolae)
library(tidyverse)
library(ExpDes.pt)
```

### Entrada de Dados

```{r}
# Definição da URL na internet do banco de dados
caminho <- "https://raw.githubusercontent.com/arpanosso/ExpAgr_2020/master/dados/Batata.txt"

# Entrada de dados
dados <- read.table(caminho,h=TRUE,sep="\t")

# Observando os dados
dados
```

### Filtrando os dados perdidos

```{r}
dados<- dados %>% 
  filter(!is.na(Y))
dados
```


### Gráfico Exploratório (Boxplot)

```{r}
dados %>% 
  ggplot(aes(x=Trat, y=Y,fill=as.factor(Trat))) + 
  geom_boxplot() +
  coord_flip() +
  labs(x="Tratamentos",y="Produção (t/ha)",fill="Tratamentos")
```


### Análise de variância utilizando as funções do pacote básico do R

```{r}
# Criando o vetor de tratamentos e da variável resposta.
trat <- as.factor(dados$Trat)
prod <- dados$Y

# Definindo o modelo para o DIC
mod <- aov(prod ~ trat)

# Quadro da análise de variância
anova(mod)
```

### Realizando o teste de Tukey

```{r}
tukey<-HSD.test(mod,"trat",group=TRUE,console = TRUE,alpha = 0.01)
```

### Calculando o CV

```{r}
ep<-sqrt(deviance(mod)/df.residual(mod))
m <- mean(prod)
CV <- 100*ep/m
CV
```

### Análise de variância utilizando a função dic do pacote ExpDes.pt

```{r}
dic(trat,prod,mcomp = "tukey",sigT = 0.01)
```

### Test t para comparar contraste

```{r}
# contruindo o vetor de médias
m <- tapply(prod,trat,mean,na.rm=TRUE)

# contruindo o vetor com a repetições de cada média
r <- tapply(prod,trat,length)

# Extraindo do modelo a SQresiduo e GLresiduo para calcular o QMRes
GLResiduo <- df.residual(mod)
QMRes <- deviance(mod)/GLResiduo


# Definindo o contraste(B72 + B1_52) vs Kennebec
c1<-c(0,1,1,-2,0) # atribua os coeficientes de acordo com a ordem das médias
(Y1=sum(m*c1))
(tobs=Y1/sqrt(sum(c1^2/r)*QMRes))
(tc5=qt(1-0.05/2,GLResiduo))
(tc1=qt(1-0.01/2,GLResiduo))

# Construção do Gráfico para interpretação
curve(dt(x,GLResiduo),-30,9,xlab="t",ylab="D(t)",las=1)
abline(v=0)
abline(v=c(tc5,-tc5,tc1,-tc1),col=2,lty=2)
abline(v=tobs,col=4,lty=1)
text(2.8,.1,expression(paste(alpha,"=2.5%")))
text(4,.02,expression(paste(alpha,"=0.5%")))
text(-2.8,.1,expression(paste(alpha,"=2.5%")))
text(-4,.02,expression(paste(alpha,"=0.5%")))
text(tobs,.05,"tobs")
```
